name: 'smi_analytics'
version: '1.0.0'
config-version: 2

profile: 'smi'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  smi_analytics:
    bronze:
      +materialized: view
      +schema: bronze
    silver:
      +materialized: table
      +schema: silver
    gold:
      +materialized: table
      +schema: gold
      +tags: ["daily"]

seeds:
  +quote_columns: false

vars:
  # Variables globales
  start_date: '2024-01-01'
  end_date: '2025-12-31'
